services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: summary-api
    networks:                 # Using this option
      - message_broker_network
    environment:
      - RABBITMQ_URL=amqp://message_broker:5672
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_add:
      - NET_ADMIN

networks:
  message_broker_network:
    name: rabbitmq_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16